#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0 
#bspc node -t floating
bspc config border_width         0 
bspc config window_gap           0 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#~/.config/polybar/launch.sh
feh --bg-scale /home/RajuArch/Downloads/milad-fakurian-E8Ufcyxz514-unsplash.jpg
#nm-applet --indicator &
#### BSPWM coloring ####
#bspc config active_border_color	      "#ffffff"
#bspc config focused_border_color	      "#ffffff"
