#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5 6 7 8 9 0 
#bspc node -t floating
##bspc config border_width         2 
##bspc config window_gap           2 
##bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# ~/.config/polybar/launch.sh
feh --bg-scale /home/RajuArch/Downloads/aurthur.jpg
#nm-applet --indicator &
#### BSPWM coloring ####
bspc config active_border_color	      #32fa7b
##bspc rule --add program state=floating rectangle=1200x600+200+30
##bspc rule -a '*' state=floating
bspc config focused_border_color	    #32fa7b
